# Generated by Django 4.0.6 on 2022-08-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_membership_project_alter_membership_user'),
        ('programs_timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtimer',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
