# Generated by Django 4.0.6 on 2022-08-01 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_membership_alter_project_users_membership_project_and_more'),
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktimer',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.task'),
        ),
    ]
