# Generated by Django 4.0.6 on 2022-07-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_owner_alter_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
    ]
