# Generated by Django 4.0.6 on 2022-07-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_properties', '0001_initial'),
        ('project', '0007_order_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='direction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_properties.directiontype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_properties.projecttype'),
        ),
    ]
