# Generated by Django 4.0.6 on 2022-07-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
