# Generated by Django 4.0.6 on 2022-07-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
